a=10
b=20
add=a+b
sub=a-b
div=a/b
mul=a*b
exp=a**b
mod=a%b
floor=a//b
print(f"result of addition={add}")
print(f"result of substraction={sub}")
print(f"result of division={div}")
print(f"result of multiplication={mul}")
print(f"result of exponential={exp}")
print(f"result of modulus={mod}")
print(f"result of floor value={floor}")